#!/usr/bin/env python3
"""
Incident Management Module
Processes transcribed text through AI analysis and formats the results
"""

import os
from datetime import datetime
from ai_analysis import AIAnalyzer


class IncidentManager:
    def __init__(self):
        self.ai_analyzer = AIAnalyzer()
        self.incident_data = None
    
    def process_incident(self, transcribed_text, polished_text=None):
        """
        Process the incident from transcribed text
        
        Args:
            transcribed_text (str): Raw transcribed text
            polished_text (str, optional): Polished transcribed text
            
        Returns:
            bool: True if successful, False otherwise
        """
        try:
            print("\n🔄 Processing incident through AI analysis...")
            
            # Use polished text if available, otherwise use raw transcription
            text_to_analyze = polished_text if polished_text else transcribed_text
            
            # Get AI analysis
            self.incident_data = self.ai_analyzer.analyze_incident(text_to_analyze)
            
            if self.incident_data:
                print("✅ AI analysis completed successfully!")
                return True
            else:
                print("❌ AI analysis failed")
                return False
                
        except Exception as e:
            print(f"❌ Error processing incident: {str(e)}")
            return False
    
    def display_incident_report(self):
        """
        Display the formatted incident report
        """
        if not self.incident_data:
            print("❌ No incident data available. Please process an incident first.")
            return
        
        # Header
        print("🚨 INCIDENT")
        
        # Display each section
        self._display_section("INCIDENT TITLE", self.incident_data.get('title', 'N/A'))
        self._display_section("WHO", self.incident_data.get('who', 'N/A'))
        self._display_section("WHAT", self.incident_data.get('what', 'N/A'))
        self._display_section("WHERE", self.incident_data.get('where', 'N/A'))
        self._display_section("IMMEDIATE ACTION", self.incident_data.get('immediate_action', 'N/A'))
        self._display_section("QUALITY CONCERNS", self.incident_data.get('quality_concerns', 'N/A'))
        self._display_section("QUALITY CONTROLS", self.incident_data.get('quality_controls', 'N/A'))
        self._display_section("RCA TOOL", self.incident_data.get('rca_tool', 'N/A'))
        self._display_section("EXPECTED INTERIM ACTION", self.incident_data.get('expected_interim_action', 'N/A'))
        self._display_section("CAPA", self.incident_data.get('capa', 'N/A'))
        
        # Footer
        print("📝 Report generated by AI-powered incident analysis system")
    
    def _display_section(self, title, content):
        """
        Display a formatted section of the incident report
        
        Args:
            title (str): Section title
            content (str): Section content
        """
        print(f"\n📋 {title}")
        if content and content.strip() and content.strip() != 'N/A':
            # Format content nicely
            lines = content.split('\n')
            for line in lines:
                if line.strip():
                    print(f"   {line.strip()}")
        else:
            print("   Information not available in transcript")
    
    def get_incident_summary(self):
        """
        Get a brief summary of the incident
        
        Returns:
            str: Incident summary or None if not available
        """
        if not self.incident_data:
            return None
        
        title = self.incident_data.get('title', 'Unknown Incident')
        what = self.incident_data.get('what', 'Details not available')
        
        # Create a brief summary
        summary = f"{title}\n\nSummary: {what[:200]}..."
        return summary

    def get_incident_data(self):
        """
        Get the raw incident data dictionary
        
        Returns:
            dict: Incident data or None if not available
        """
        return self.incident_data
    
    def validate_incident_data(self):
        """
        Validate that incident data contains meaningful information
        
        Returns:
            bool: True if valid, False otherwise
        """
        if not self.incident_data:
            return False
        
        # Check if at least some key fields have meaningful content
        key_fields = ['title', 'what', 'who']
        
        for field in key_fields:
            content = self.incident_data.get(field, '')
            if content and content.strip() and content.strip() != 'N/A' and 'not available' not in content.lower():
                return True
        
        return False
    
    def display_quick_summary(self):
        """
        Display a quick summary of the incident
        """
        if not self.incident_data:
            print("❌ No incident data available")
            return
        
        title = self.incident_data.get('title', 'Unknown Incident')
        what = self.incident_data.get('what', 'Details not available')
        
        print(f"\n📄 QUICK SUMMARY")
        print("-" * 16)
        print(f"Title: {title}")
        print(f"Description: {what[:100]}{'...' if len(what) > 100 else ''}")
    
    def export_incident_data(self):
        """
        Export incident data as a dictionary for external use
        
        Returns:
            dict: Formatted incident data
        """
        if not self.incident_data:
            return None
        
        return {
            'incident_title': self.incident_data.get('title', ''),
            'who': self.incident_data.get('who', ''),
            'what': self.incident_data.get('what', ''),
            'where': self.incident_data.get('where', ''),
            'immediate_action': self.incident_data.get('immediate_action', ''),
            'quality_concerns': self.incident_data.get('quality_concerns', ''),
            'quality_controls': self.incident_data.get('quality_controls', ''),
            'rca_tool': self.incident_data.get('rca_tool', ''),
            'expected_interim_action': self.incident_data.get('expected_interim_action', ''),
            'capa': self.incident_data.get('capa', ''),
            'timestamp': datetime.now().isoformat()
        }